name: Docs Validation CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        
    - name: Сheck links
      run: |
        pip install pytest-check-links
        pytest --check-links tests/ README.md

    - name: Сodespell
      run: |
        pip install codespell
        codespell --skip=".git,*.pyc" --ignore-words-list="ist,ot"
        
    - name: Run repository structure and content tests
      run: |
        pytest tests/ -v
